language: cpp
compiler:
# - gcc
  - clang
before_install: "mkdir build; cd build;"
install: "cmake -G \"Unix Makefiles\" ../ && make"
script:
  >
    ./lspl3 ../lspl3config.json ../tests/Patterns.txt ../tests/2001_A_Space_Odyssey.json cout
branches:
  only:
    - master
notifications:
  email: false
