language: cpp
compiler:
  - gcc
  - clang
before_install: "mkdir build; cd build;"
install: "cmake -G \"Unix Makefiles\" ../ && make"
script:
  >
    ./lspl3.exe lspl3config.json tests/Patterns.txt tests/2001_A_Space_Odyssey.json cout
branches:
  only:
    - master
